icon-sender: prefer xcffib module over xpyb
xpyb in Fedora 26 (and probably others) have problems with parsing X
events, like this:

    Traceback (most recent call last):
      File "/usr/lib/qubes/icon-sender", line 155, in <module>
        retriever.watch_and_send_icons()
      File "/usr/lib/qubes/icon-sender", line 136, in watch_and_send_icons
        [xproto.EventMask.SubstructureNotify])
      File "/usr/lib64/python2.7/site-packages/xcb/xproto.py", line 1400, in ChangeWindowAttributesChecked
        for elt in xcb.Iterator(value_list, 15, 'value_list', False):
    xcb.Exception: Too few items in 'value_list' list (expect 15).

QubesOS/qubes-issues#1495

(cherry picked from commit dd959a0aedf3b32b57c489808a388fd6782ddb88)